project:
  type: website
  resources:
    - CNAME
    - toolbox/*.html
    - toolbox/*.css

website:
  title: "Prof. Rosi"
  site-url: "https://casimir91.github.io"
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: didattica/index.qmd
        text: Didattica
      - href: lab/index.qmd
        text: Lab
      - href: edtech/index.qmd
        text: EdTech
      - href: toolbox/index.qmd
        text: Toolbox
      - href: stories/index.qmd
        text: Stories
    right:
      - href: chi-sono.qmd
        text: Chi sono
      - { icon: linkedin, href: "https://www.linkedin.com/in/ermes-f-rosi/" }

format:
  html:
    theme:
      light: sandstone
      dark: [darkly, custom-dark.scss]
    respect-user-color-scheme: true
    toc: true
