---
title: "Chi sono"
---

Sono un fisico di formazione e insegno matematica e fisica al Liceo STEAM International di Bologna. Dopo la laurea magistrale, con una tesi in didattica della fisica, mi sono occupato di divulgazione scientifica e poi di insegnamento.

Considero la scienza una materia che necessita di un coinvolgimento attivo. Lo studente deve imparare a confrontarsi con sfide e problemi reali perché solo in questo modo imparerà a far parte del mondo, scegliendo con consapevolezza un futuro desiderabile. Per interiorizzare i metodi e gli strumenti propri dell'esplorazione scientifica, la mia metodologia didattica integra alla lezione tradizionale project-based learning, inquiry-based learning, microcontrollori e codice, portando la teoria dentro uno strumento da costruire per poter misurare il mondo.

Fuori dall'aula mi interessa la costruzione di una rete con gli stakeholder del territorio, al fine di esplorare il tessuto sociale che mi circonda.

Credo molto nel potere della comunicazione e dell'interattività. Da questo interesse nascono le mie slide e questo sito che le ospita: il non-luogo dove le mie idee diventano materia, cioè la mia didattica, la mia passione per le nuove tecnologie, le mie riflessioni sul mondo in cui vivo. Questo sito è per chi non ha mai smesso di essere curioso e cerca un luogo sicuro in cui esplorare il cosmo.
